### ISSUE TITLE
Fehler beim Kompilieren

### ISSUE THREAD

**Issue by Byllyy** [DIYDave/ESP8266-Alarmclock#1]
Hallo und Danke für dein Projekt das mich zum Nachbau inspiriert hat.

Als Anfänger versuche ich deinen Code mit dem Arduinoprogramm auf den ESP8266 zu spielen.
Leider kommt schon beim Überprüfen/Kompilieren der Fehler:
"no matching function for call to 'NextionButton::attachCallback(Handler*)'

Kannst Du mir einen Tipp geben wie ich weiter komme?
Vielen Dank,
Byllyy

**Comment by DIYDave** [comment]
With new version 1.10 and platformIO IDE everything should work fine.
